# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9524f55369b5e1de7f91e9a85d7d72807df09c3b9b7d312199fba18b12e86ad309c746bef682bbe20e5ce4f80fcd48f07dec86324ce55bf2cee84ec6818e266

test:
  secret_key_base: 01844fa63056c01968dc732ed184028963f09c0d01405ec34cf03ee1594ae52a2199a514bdda029b07984b33faf1bf5cd6c9ee2e9af2da4707a2dbbfeeee256e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
